### ISSUE TITLE
Can't compile example

### ISSUE THREAD

**Issue by fkemper** [epsilonrt/modbus-ethernet#1]
When i try to compile the example i get this error-messages:

```
/tmp/.arduinoIDE-unsaved2023226-2507-1391udn.c6cx/TempSensor/TempSensor.ino: In function 'void setup()':
/tmp/.arduinoIDE-unsaved2023226-2507-1391udn.c6cx/TempSensor/TempSensor.ino:29:8: error: 'class ModbusEthernet' has no member named 'addIreg'
     mb.addIreg(SENSOR_IREG);
        ^~~~~~~
/tmp/.arduinoIDE-unsaved2023226-2507-1391udn.c6cx/TempSensor/TempSensor.ino: In function 'void loop()':
/tmp/.arduinoIDE-unsaved2023226-2507-1391udn.c6cx/TempSensor/TempSensor.ino:42:11: error: 'class ModbusEthernet' has no member named 'Ireg'
        mb.Ireg(SENSOR_IREG, analogRead(sensorPin));
```

I installed the necessary libs

Modbus@1.0.0

I use Arduino-IDE:

Version: 2.0.3
Date: 2022-12-05T09:27:52.215Z
CLI Version: 0.29.0 [76251df9]

**Comment by epsilonrt** [comment]
![image](https://user-images.githubusercontent.com/13524484/227782255-6473b10d-2899-47b3-a20b-f68c2511f025.png)

I don't think you installed the correct libraries. You must install the library which is indicated in the README, this one and not another. Mine is called Modbus-Arduino

My Modbus libraries are now installable from the Arduino and Platformio library manager:

- [Library Manager](https://cse.google.com/cse?cx=008830049033802121810%3Azgsyidwem5w&q=epsilonrt)  
- [Pio Registry]( https://registry.platformio.org/search?q=epsilonrt)

**Comment by fkemper** [comment]
Hi,
your are right. After i deinstalled all libs and install the your lib and the libs wich indicated in the README i could compile the example. I don't know what lib was wrong installed but now it works.
